kind: ReplicationController
id: connection-controller
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector: 
    name: connection
    version: v1
  podTemplate:
    labels:
      name : connection
      version: v1
    desiredState:
      manifest:
        containers:
          - name: connection
            image: clemble/connection:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 8080
                hostPort: 8080
                protocol: TCP
            labels:
              name : connection
              version: v1