kind: ReplicationController
id: email-controller
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: email
    version: v1
  podTemplate:
    labels:
      name : email
      version: v1
    desiredState:
      manifest:
        containers:
          - name: email
            image: clemble/email:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 8080
                hostPort: 8080
                protocol: TCP
            labels:
              name : email
              version: v1
