kind: ReplicationController
id: payment-v5
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: payment
    version: v5
  podTemplate:
    labels:
      name : payment
      version: v5
    desiredState:
      manifest:
        containers:
          - name: payment
            image: clemble/payment:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10009
                hostPort: 10009
                protocol: TCP
            labels:
              name : payment
              version: v5
