kind: ReplicationController
id: profile-v2
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector: 
    name: profile
    version: v2
  podTemplate:
    labels:
      name : profile
      version: v2
    desiredState:
      manifest:
        containers:
          - name: profile
            image: clemble/profile:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10012
                hostPort: 10012
                protocol: TCP
            labels:
              name : profile
              version: v2