id: rabbitmq
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: rabbitmq
        image: rabbitmq
        ports: 
          - containerPort: 5672
            hostPort: 5672
  labels: 
    app : rabbitmq
