id: redis
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: redis
        image: redis
        ports: 
          - containerPort: 6379
            hostPort: 6379
  labels: 
    app : redis
