kind: ReplicationController
id: social-v11
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector: 
    name: social
    version: v11
  podTemplate:
    labels:
      name : social
      version: v11
    desiredState:
      manifest:
        containers:
          - name: social
            image: clemble/social:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10014
                hostPort: 10014
                protocol: TCP
            labels:
              name : social
              version: v11