kind: ReplicationController
id: tag-controller
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: tag
    version: v1
  podTemplate:
    labels:
      name : tag
      version: v1
    desiredState:
      manifest:
        containers:
          - name: tag
            image: clemble/tag:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 8080
                hostPort: 8080
                protocol: TCP
            labels:
              name : tag
              version: v1
