kind: ReplicationController
id: connection-v3
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector: 
    name: connection
    version: v3
  podTemplate:
    labels:
      name : connection
      version: v3
    desiredState:
      manifest:
        containers:
          - name: connection
            image: clemble/connection:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10010
                hostPort: 10010
                protocol: TCP
            labels:
              name : connection
              version: v3