kind: ReplicationController
id: construction-v7
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: construction
    version: v7
  podTemplate:
    labels:
      name : construction
      version: v7
    desiredState:
      manifest:
        containers:
          - name: construction
            image: clemble/construction:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10005
                hostPort: 10005
                protocol: TCP
            labels:
              name : construction
              version: v7
