kind: ReplicationController
id: email-v2
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: email
    version: v2
  podTemplate:
    labels:
      name : email
      version: v2
    desiredState:
      manifest:
        containers:
          - name: email
            image: clemble/email:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10001
                hostPort: 10001
                protocol: TCP
            labels:
              name : email
              version: v2
