kind: ReplicationController
id: feed-v2
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector: 
    name: feed
    version: v2
  podTemplate:
    labels:
      name : feed
      version: v2
    desiredState:
      manifest:
        containers:
          - name: feed
            image: clemble/feed:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10011
                hostPort: 10011
                protocol: TCP
            labels:
              name : feed
              version: v2