kind: ReplicationController
id: management-v4
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: management
    version: v4
  podTemplate:
    labels:
      name : management
      version: v4
    desiredState:
      manifest:
        containers:
          - name: management
            image: clemble/management:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10006
                hostPort: 10006
                protocol: TCP
            labels:
              name : management
              version: v4
