kind: ReplicationController
id: suggestion-v2
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: suggestion
    version: v2
  podTemplate:
    labels:
      name : suggestion
      version: v2
    desiredState:
      manifest:
        containers:
          - name: suggestion
            image: clemble/suggestion:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10007
                hostPort: 10007
                protocol: TCP
            labels:
              name : suggestion
              version: v2
