id: system-notification
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    containers:
      - name: system-notification
        image: clemble/rabbitmq
        ports: 
          - containerPort: 5672
            hostPort: 5672
labels: 
  app : system-notification
