kind: ReplicationController
id: tag-v2
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: tag
    version: v2
  podTemplate:
    labels:
      name : tag
      version: v2
    desiredState:
      manifest:
        containers:
          - name: tag
            image: clemble/tag:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10016
                hostPort: 10016
                protocol: TCP
            labels:
              name : tag
              version: v2
