kind: ReplicationController
id: webv3
apiVersion: v1beta1
desiredState:
  replicas: 1
  replicaSelector:
    name: web
    version: v3
  podTemplate:
    labels:
      name : web
      version: v3
    desiredState:
      manifest:
        containers:
          - name: web
            image: clemble/web:latest
            imagePullPolicy : PullAlways
            ports:
              - containerPort: 10001
                hostPort: 10001
                protocol: TCP
            labels:
              name : web
              version: v3